name: travel_mate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  curved_navigation_bar: ^1.0.6
  google_fonts: ^5.0.0 # Use the latest version
  dynamic_tabbar: ^1.0.9
  carousel_slider: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/